//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belyaev_UP1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UP_1Entities : DbContext
    {
        public UP_1Entities()
            : base("name=UP_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<AppStatus> AppStatus { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DeffectType> DeffectType { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
